// <auto-generated />
using System;
using GameStation.DAL.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameStation.DAL.Migrations
{
    [DbContext(typeof(GameStationContext))]
    partial class GameStationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameStation.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Picture1")
                        .HasMaxLength(400);

                    b.Property<string>("Picture2")
                        .HasMaxLength(400);

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new { CategoryID = 1, CategoryName = "FPS", Description = "Birinci şahıs nişancı oyunları.", IsActive = true },
                        new { CategoryID = 2, CategoryName = "TPS", Description = "Üçüncü şahıs nişancı oyunları.", IsActive = true },
                        new { CategoryID = 3, CategoryName = "RPG", Description = "Rol yapma oyunları", IsActive = true },
                        new { CategoryID = 4, CategoryName = "Strategy", Description = "Strateji oyunları", IsActive = true },
                        new { CategoryID = 5, CategoryName = "Simülasyon", Description = "Simülasyon oyunları", IsActive = true },
                        new { CategoryID = 6, CategoryName = "Aksiyon", Description = "Aksiyon oyunları", IsActive = true }
                    );
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.Customer", b =>
                {
                    b.Property<string>("CustomerID");

                    b.Property<string>("Address")
                        .HasMaxLength(200);

                    b.Property<string>("AltEmail")
                        .HasMaxLength(40);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .HasMaxLength(20);

                    b.Property<string>("Country")
                        .HasMaxLength(20);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email")
                        .HasMaxLength(40);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("Gender");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Mobile1")
                        .HasMaxLength(20);

                    b.Property<string>("Mobile2")
                        .HasMaxLength(20);

                    b.Property<string>("Notes")
                        .HasMaxLength(250);

                    b.Property<string>("Organization")
                        .HasMaxLength(50);

                    b.Property<string>("Password");

                    b.Property<string>("Phone1")
                        .HasMaxLength(20);

                    b.Property<string>("Phone2");

                    b.Property<string>("Picture")
                        .HasMaxLength(400);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20);

                    b.Property<string>("State")
                        .HasMaxLength(20);

                    b.Property<string>("Status")
                        .HasMaxLength(20);

                    b.Property<string>("UserName");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.CustomIdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new { Id = "bace2fe6-0871-41bd-b614-931227376627", ConcurrencyStamp = "5aa88f8c-b1d0-4cbc-b74b-b62e568127b7", Name = "Admin", NormalizedName = "ADMIN" }
                    );
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.CustomIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new { Id = "ed569773-7f8d-4712-9b43-5ae3ad709632", AccessFailedCount = 0, ConcurrencyStamp = "2dbd8457-2052-42b9-a682-00fc5b6cd01c", Email = "admin@admin.com", EmailConfirmed = true, LockoutEnabled = false, NormalizedEmail = "admin@admin.com", NormalizedUserName = "admin", PasswordHash = "AQAAAAEAACcQAAAAEH6YT78fMtbqCuj9E5GIbl8zfNXkYww0zuj8Rzn4Emf9G3AXKDsNBmdXeFDZ2A3aIA==", PhoneNumberConfirmed = false, SecurityStamp = "", TwoFactorEnabled = false, UserName = "admin" }
                    );
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CancelOrder");

                    b.Property<bool>("Deliver");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount");

                    b.Property<DateTime>("DispatchDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Dispatched");

                    b.Property<bool>("IsCompleted");

                    b.Property<string>("Notes")
                        .HasMaxLength(150);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderDetailID");

                    b.Property<int>("PaymentID");

                    b.Property<bool>("Shipped");

                    b.Property<DateTime>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShippingDetailID");

                    b.Property<decimal?>("Taxes");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("money");

                    b.HasKey("OrderID");

                    b.HasIndex("OrderDetailID");

                    b.HasIndex("PaymentID");

                    b.HasIndex("ShippingDetailID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerID")
                        .IsRequired();

                    b.Property<decimal>("Discount");

                    b.Property<bool>("IsCompleted");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance")
                        .HasColumnType("money");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("DebitAmount")
                        .HasColumnType("money");

                    b.Property<DateTime>("PaymentDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentTypeID");

                    b.HasKey("PaymentID");

                    b.HasIndex("PaymentTypeID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("PaymentTypeID");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("CategoryID");

                    b.Property<decimal>("Discount");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(1500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Notes")
                        .HasMaxLength(250);

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("money");

                    b.Property<string>("Picture1")
                        .HasMaxLength(500);

                    b.Property<string>("Picture2")
                        .HasMaxLength(500);

                    b.Property<string>("Picture3")
                        .HasMaxLength(500);

                    b.Property<string>("Picture4")
                        .HasMaxLength(500);

                    b.Property<bool?>("ProductAvailable");

                    b.Property<string>("QuantityPerUnit")
                        .HasMaxLength(50);

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Size")
                        .HasMaxLength(30);

                    b.Property<int>("SupplierID");

                    b.Property<int?>("UnitOnOrder");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.Property<string>("UnitWeight")
                        .HasMaxLength(30);

                    b.Property<int>("UnitsInStock");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Products");

                    b.HasData(
                        new { ProductID = 1, AltText = "Rimworld", CategoryID = 4, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/rimworld_logo.png", LongDescription = "The futuristic plot originally revolved around three characters being stranded on a planet located in the frontiers of known space (a 'rim world'), where their space liner crashed. The game is set in a universe where faster-than-light travel and superluminal communication are, so far, impossible, making large galactic empires inherently unfeasible. With its release on Steam the game came with the addition, among other things, of a scenario editor, allowing users to choose and modify different starting plots, with different numbers of characters, starting items and map effects available; however, the location of these plots still remained the same, that is, still on a 'rim world'", Name = "RimWorld", ShortDescription = "RimWorld is a top-down construction and management simulation video game by Montreal-based developer Ludeon Studios. Originally called Eclipse Colony, it was initially released as a Kickstarter crowdfunding project in early access for Microsoft Windows, macOS, and Linux in November 2013, and was officially released on October 17, 2018.", SupplierID = 1, UnitPrice = 50m, UnitsInStock = 0 },
                        new { ProductID = 2, AltText = "Mount & Blade II: Bannerlord", CategoryID = 1, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/bannerlord_logo.png", LongDescription = "27 Eylül 2012'de bir Türk şirketi olan TaleWords tarafından duyurulmuştur. Oyunun Grafikleri daha iyi gölgeleme ve daha yüksek detaylı modellerle önceki oyun olan Mount & Blade: Warband'a göre belirgin bir şekilde daha iyi hâle getirilmiştir. Karakter animasyonları hareket yakalama (motion capture) teknolojisi kullanılarak oluşturulmuş ve yüz animasyonları da canlandırılan duygularla iyileştirilerek güncelleneceği söylendi.", Name = "Bannerlord", ShortDescription = "Mount & Blade II: Bannerlord, Orta Çağ temalı bir rol yapma oyunu olan Mount & Blade serisinin bir oyunudur. Oyun, Türk firması TaleWorlds tarafından geliştiştirilmektedir. Oyun Steam'de Ekim 2016'da çıkmıştır. Fakat oyun için bir indirme imkanı sunulmamıştır. Gamescom 2019'da oyunun erken erişim tarihi verilmiş. Ayrıca bu çıkış tarihi Mount & Blade:Warband'ın 10. yılına denk gelmiş olacak.", SupplierID = 1, UnitPrice = 160m, UnitsInStock = 0 },
                        new { ProductID = 3, AltText = "Grand Theft Auto V", CategoryID = 3, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/gtav_logo.png", LongDescription = "Oyunda Michael, Franklin ve Trevor isminde üç farklı karakter mevcuttur. Oyundaki üç karakterden her birinin farklı alanlarda farklı yetenekleri ve güçleri vardır. Örneğin, Trevor eski bir savaş pilotu olduğu için uçak, jet, helikopter ve diğer hava araçlarını kullanma konusunda diğer karakterlerden daha iyidir. Michael ise eski bir banka soyguncusu olduğundan silah kullanma konusunda diğerlerinden daha iyidir. Franklin ise araç hırsızı olduğundan otomobil ve motosiklet sürme konusunda diğerlerine göre çok daha ustadır. Oyuncular karakterler arasında geçiş yapabilme imkanına sahiplerdir.", Name = "Grand Theft Auto V", ShortDescription = "Grand Theft Auto V (kısaca GTA V veya GTA 5), Rockstar North tarafından geliştirilen ve Rockstar Games tarafından yayımlanan açık uçlu aksiyon-macera tarzı video oyunu. Grand Theft Auto serisinin beşinci oyunudur. 17 Eylül 2013 tarihinde PlayStation 3 ve Xbox 360 için piyasaya çıkmıştır.", SupplierID = 1, UnitPrice = 160m, UnitsInStock = 0 },
                        new { ProductID = 4, AltText = "Crusader Kings 2", CategoryID = 4, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/ck2_logo.png", LongDescription = "The game is a dynasty simulator where the player controls a Medieval dynasty from 1066 to 1453, though the DLC The Old Gods and Charlemagne allow for earlier start dates of 867 and 769, respectively. Through the strategic use of war, marriages and assassinations among many other things, the player works to achieve success for their dynasty.", Name = "Crusader Kings 2", ShortDescription = "Crusader Kings II is a grand strategy game set in the Middle Ages, developed by Paradox Development Studio and published by Paradox Interactive as a sequel to Crusader Kings.", SupplierID = 1, UnitPrice = 28m, UnitsInStock = 0 },
                        new { ProductID = 5, AltText = "Europa Universalis 4", CategoryID = 4, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/eu4_logo.png", LongDescription = "Oyunun temel ilkeleri dizinin daha önceki oyunlarına benzer. Oyuncu tek oyuncu olarak yapay zekaya karşı, çok oyuncu olarak diğer insanlara veya beraber yapay zekâya karşı oynayabilir. Bir devletin denetimini ele alarak diplomasi, politika ve askeri olanakları kullanmak ve diğer devletlere karşı galip olmak hedeflenir. Oyuncu birçok alternatif araç ile büyümeye çalışır. Oyunun zaman dilimi 1444 ila 1821 arasındadır, bu tarihler içerisinde oyuna oyunda yer alan istendiği ülkeyle, istendiği tarihte başlanabilir.", Name = "Europa Universalis 4", ShortDescription = "Europa Universalis IV, Paradox Development Studio tarafından geliştirilmiş ve Paradox Interactive tarafından yayımlanmış strateji oyunu. Europa Universalis serisinin 4. üyesidir.EUIV ya da EU4 olarak da bilinir.", SupplierID = 1, UnitPrice = 60m, UnitsInStock = 0 },
                        new { ProductID = 6, AltText = "Hearts Of Iron 4", CategoryID = 4, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/hoi4_logo.png", LongDescription = "Oyuncular 1936 ve 1939 olmak üzere iki başlangıç tarihinden birini seçip ülkeleriyle savaşta zafer almaya çalışabilir. Oyun 2014 Ocak ayında duyuruldu. 2015 senesinin ilk çeyreğinde çıkması planlanıyordu ancak sonradan 2015'in ikinci çeyreğine ertelendi.[1] Johan Andersson oyunun istenilen seviyede olmadığını belirtip daha ileri bir tarihte çıkacağını açıkladı. 15 Mart 2016'da oyunun 6 Haziran tarihinde çıkacağı duyuruldu ve o tarihte çıktı.", Name = "Hearts Of Iron 4", ShortDescription = "Hearts of Iron IV Paradox Development Studio tarafından geliştirilen ve Paradox Interactive tarafından yayımlanan strateji oyunu. Hearts of Iron III'ün devam oyunudur, diğer Hearts of Iron serisi oyunları gibi II. Dünya Savaşı'na odaklanır.", SupplierID = 1, UnitPrice = 60m, UnitsInStock = 0 },
                        new { ProductID = 7, AltText = "The Elder Scrolls V: Skyrim", CategoryID = 3, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/skyrim_logo.png", LongDescription = "Elder Scrolls serisinin geleneksel açık uçlu oynanış özelliği Skyrim'de de devam ettirildi. Oyuncu at üstünde veya yürüyerek ülkeyi dolaşabilir ve şehir, kasaba, zindan gibi yerler bir kez keşfedildikten sonra bu bölgelere hızlı seyahat edebilir. Görevler oyuncuya NPC'ler tarafından ya da Radyant Hikâye sistemi aracılığıyla verilir. Radyant Hikâye sistemi bir nevi oyuncunun yaptığı tüm seçimleri kaydeder ve oyundaki bazı görevlerin akışını değiştirir. Bu sistem, görev olarak, keşfedilmemiş yeni zindanlar oluşturur ve oyuncunun ülkeyle olan etkileşiminde değişiklikler yapar.", Name = "The Elder Scrolls V: Skyrim", ShortDescription = "The Elder Scrolls V: Skyrim (yaygın olarak bilinen ismi Skyrim), Bethesda Game Studios tarafından geliştirilip Bethesda Softworks tarafından piyasaya sürülen serbest dünya tipi aksiyon RPG video oyunudur. The Elder Scrolls serisinin The Elder Scrolls IV: Oblivion'dan sonra gelen toplamda beşinci uyarlamasıdır.", SupplierID = 1, UnitPrice = 30m, UnitsInStock = 0 },
                        new { ProductID = 8, AltText = "Fallout 4", CategoryID = 3, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/fallout4_logo.png", LongDescription = "Fallout 4, oynanış olarak Fallout 3'e benzer olacak, önceki oyunda olduğu gibi birinci görüş şahısı ya da üçüncü görüş şahısı ile oynanabilecek. Yeni özellik olarak ayrı parçalardan oluşabilecek zırh, ayrıntılı crafting sistemi, dinamik konuşma sistemi sayılabilir. Yeni crafting sistemiyle oyundaki bütün eşyalar belli bir parça için istenilen olabilecek. Dogmeat bu oyunda ölümsüz olacak. Oyuncular haritada isteği zaman istediği yere gidebilecek.Oyunda 50 temel silah çeşidi bulunacak ve çeşitli modifikasyonlar yapılarak 700'ün üzerinde farklı tarz silah oluşturabilecek. Power Armor, jetpack gibi çeşitli eşyalarla güçlendirilebilecek. Oyuna gelen yeni bir özellik ise kendi evini baştan aşağıya yenileyip değiştirebilmektir. Oyuncu, oyundaki eşyaları evi için kullanabilecek. Tüccarlar, şehrin birçok yerinde olup ev için malzeme satacak. Oyuncular, kendi evleri için taret ve tuzak gibi çeşitli savunma araçları inşa edebilecek.", Name = "Fallout 4", ShortDescription = "Fallout 4, Bethesda Game Studios'un geliştiriciliğini yaptığı ve Bethesda Softworks'ün yayımcılığını yaptığı açık dünya Aksiyon rol yapma oyunudur. Fallout serisinin beşinci büyük oyunudur ve Microsoft Windows, PlayStation 4 ve Xbox One için 10 Kasım 2015'te yayımlanmıştır.", SupplierID = 1, UnitPrice = 133m, UnitsInStock = 0 },
                        new { ProductID = 9, AltText = "Counter-Strike: Global Offensive", CategoryID = 1, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/csgo_logo.png", LongDescription = "Serinin önceki oyunları gibi Global Offensive, görev tabanlı birçok oyunculu birinci şahıs nişancı oyunudur. Oyuncular ilk önce görevleri tamamlamak veya düşman takımı yok etmek için teröristler (Terrorists) veya terörle mücadele ekibi (Counter-Terrorists) takımlarından birini seçerler. Örneğin, yıkım haritalarında (de_) teröristler bomba kurmaya çalışırken, terörle mücadele bombanın kurulmasını engellemeye veya kurulmuş bombayı imha etmeye çalışır. Global Offensive'e önceki oyunlardaki görevlere ek olarak silah yarışı (arms race) denilen bir mod eklenmiş, bu modla birlikte klasik Counter-Strike haritalarının yanında farklı haritalar da oyuna dahil edilmiştir.", Name = "Counter-Strike: Global Offensive", ShortDescription = "Counter-Strike: Global Offensive (kısaca CS: GO), Valve ve Hidden Path Entertainment tarafından geliştirilen çevrim içi bir birinci şahıs nişancı türünde aksiyon oyunudur.", SupplierID = 1, UnitPrice = 20m, UnitsInStock = 0 },
                        new { ProductID = 10, AltText = "Half-Life", CategoryID = 1, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/half-life_logo.png", LongDescription = "Oyuncu, bir ışınlanma deneyinin ters gitmesi sonucu Xen olarak bilinen başka bir boyuttan Black Mesa Araştırma Tesisine ışınlanan uzaylılardan savaşarak ve bulmacaları çözerek tesisden kaçmaya çalışan Dr. Gordon Freeman rolünü üstleniyor. Zamanın diğer oyunlarına göre Half-Life'da ara sahneler yoktur. Oyuncu her zaman Freeman'nı kontrol ediyor. Her zaman onun gözünden görüyor. Valve'nin kurucularından olan Gabe Newell ''ekip olarak oyunun sadece ateş etmeye meyilli bir oyundan çok daha fazla olmasını istedik.'' demiştir.", Name = "Half-Life", ShortDescription = "Half-Life, 1998 yılında Sierra Studios tarafından yayımlanan ve Valve tarafında üretilen birinci şahıs nişancı bilim-kurgu video oyunudur. Oyun, serinin ilk oyunu olmakla beraber aynı zamanda Valve'nin ürettiği ilk oyundur.", SupplierID = 1, UnitPrice = 18m, UnitsInStock = 0 },
                        new { ProductID = 11, AltText = "The Sims 4", CategoryID = 5, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/sims4_logo.png", LongDescription = "The Sims 4, serinin önceki oyunları gibi yaşam simülasyonu oyunudur. Oyuncular bir Sim karakteri yaratırlar ve oyunda farklı Sim kişiliklerini keşfederek oyuna yön verirler. Simler daha önceki oyunlardan farklı olarak aynı anda iki fiziksel eylemi gerçekleştirebilir. Ayrıca Simlerin modları da oyun akışını değiştirebilir. Örneğin kızgın ya da heyecanlı bir Sim, verilen bir görevi daha hızlı yapar.", Name = "The Sims 4", ShortDescription = "The Sims 4, Maxis ve The Sims Studio tarafından geliştirilen ve Electronic Arts tarafından yayınlanan 2014 tarihli yaşam simülasyonu oyunudur. Electronic Arts, 6 Mayıs 2013 tarihinde bir duyuru yaparak oyunu 2014 yılında piyasaya süreceğini ve Microsoft Windows, Mac OS X platformlarında oynanacağını bildirdi.", SupplierID = 2, UnitPrice = 200m, UnitsInStock = 0 },
                        new { ProductID = 12, AltText = "Battlefield 4", CategoryID = 1, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/battlefield4_logo.png", LongDescription = "Oyunun çerçeveleri Battlefield 3’e göre genel olarak aynı kaldı. Çerçevenin sol altında harita ve pusula, ve görevle ilgili hedefler; sağ altında ise silah bilgileri yer almaktadır. Mini harita ve oyunun ana menüsü, 3 önemli şeyi belirtmektedir. Bunlar, dostların mavi ile gösterilmesi, ekip arkadaşlarının yeşil ile gösterilmesi, düşmanların ise turuncu ya da kırmızı ile gösterilmesidir. Oyunda Battlefield 3’te olduğu gibi bazı silahların iki çeşit atış modu vardır; bunlardan biri tekli atışken, diğeri de çoklu atış modudur.", Name = "Battlefield 4", ShortDescription = "Battlefield 4 bir birinci şahıs nişancı video oyunudur ve İsveç’teki EA Digital Illusions CE (DICE) tarafından yapılıp Electronic Arts tarafından yayınlanmıştır. Oyun 2011’de çıkan Battlefield 3’ün devamıdır.", SupplierID = 2, UnitPrice = 100m, UnitsInStock = 0 },
                        new { ProductID = 13, AltText = "FIFA 19", CategoryID = 1, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/fifa19_logo.png", LongDescription = "FIFA serisinin 26. oyunudur. FIFA 18 oyununda da olduğu gibi oyunun standart sürümünün kapağında Cristiano Ronaldo yer almıştır. Ancak, İspanyol kulübü Real Madrid'den İtalyan ekibi Juventus'a beklenmedik transferi sonrası kapak resmi yenilenmiştir. Ayrıca Şampiyonlar sürümünün kapağında Neymar yer almıştır. Şubat 2019'da düzenlenen standart sürümün kapağında Neymar, Kevin De Bruyne ve Paulo Dybala'ya yer verilmiştir.", Name = "FIFA 19", ShortDescription = "FIFA 19, EA Vancouver tarafından geliştirilen ve Electronic Arts şirketinin yayımcılığını yaptığı spor simülasyon video oyunu olarak sunulan FIFA serisi. 6 Haziran 2018 tarihinde yapılan E3 2018 basın konferansında, oyunun 28 Eylül 2018 tarihinde PlayStation 3, PlayStation 4, Xbox 360, Xbox One, Nintendo Switch ve Microsoft Windows platformlarında çıkmış olacağı açıklanmıştır.", SupplierID = 2, UnitPrice = 245m, UnitsInStock = 0 },
                        new { ProductID = 14, AltText = "A Way Out", CategoryID = 6, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/awayout_logo.png", LongDescription = "A Way Out is an action-adventure game played from a third-person perspective. It is specifically designed for split-screen cooperative multiplayer, which means that it must be played with another player through either local or online play. In the game, players control Leo and Vincent, two convicted prisoners who must break out of prison and stay on the run from authorities. As the story of both protagonists is told simultaneously, their progress may not be synchronized, which may result in one player being able to control their character, while another is watching a cutscene. Players need to cooperate with each other in order to progress, and each situation can be approached differently, with both characters taking different roles.", Name = "A Way Out", ShortDescription = "A Way Out is an action-adventure game developed by Hazelight Studios and published by Electronic Arts under their EA Originals program. It is the second video game to be directed by Josef Fares after Brothers: A Tale of Two Sons. The game has no single-player option: it is only playable in either online or local split screen co-op between two players.", SupplierID = 2, UnitPrice = 155m, UnitsInStock = 0 },
                        new { ProductID = 15, AltText = "Dead Space 3", CategoryID = 2, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/deadspace3_logo.png", LongDescription = "In Dead Space 3, Isaac Clarke teams up with EarthGov Sergeant John Carver as they travel to Tau Volantis, an ice-covered planet, to end the Marker and Necromorph threat for good. Development of the game began after the completion of Dead Space 2.It is the only game in the Dead Space series to feature online co - op. The game received positive reviews from game critics upon release; reviewers praised the game's rewarding action gameplay, although criticism was directed at the focus on action over horror, as well as a weak and unfocused story compared to its predecessors. Despite poor sales, EA and Visceral expressed interest in a sequel. However, Visceral Games was shut down in 2017, and no confirmation that a new installment in the series is being developed by another studio.", Name = "Dead Space 3", ShortDescription = "Dead Space 3 is a survival horror action-adventure video game developed by Visceral Games and published by Electronic Arts. Announced at E3 2012 and released internationally in February 2013, it is the sequel to Dead Space 2 and the third main entry in the Dead Space series.", SupplierID = 2, UnitPrice = 200m, UnitsInStock = 0 },
                        new { ProductID = 16, AltText = "Command & Conquer Red Alert 3", CategoryID = 4, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/cc-redalert_logo.png", LongDescription = "Sovyetler ile Müttefikler arasındaki savaşta müttefikler üstünlüğü sağlamak ve Sovyetler savaşı kaybetmek üzereydi. Bunun üzerine Premier Cherdenko, gizli yürüttüğü bir zaman makinesi projesini hayata geçirmeye karar vermişti.Zaman makinesi tam olarak hazır değildi ve bu makineyi icat eden doktor Zelisnsky Cherdenko'yu durdumayı çalışmıştı ama Cherkenko yanına General Krukov'u da alıp geçmişe gitmeye kararlıydı.", Name = "Command & Conquer Red Alert 3", ShortDescription = "Command & Conquer: Red Alert 3 (Kısaca C&C:RA3) EA Los Angeles tarafından geliştirilip, Electronic Arts tarafından 2008'de yayınlanan bir gerçek zamanlı strateji oyunu. 14 Şubat 2008'de EA LA tarafından geliştirildiği duyuruldu ve 28 Ekim 2008'de Windows tabanlı bilgisayarlar için; 11 Kasım'da Xbox 360 konsolu için yayınlandı.", SupplierID = 2, UnitPrice = 200m, UnitsInStock = 0 },
                        new { ProductID = 17, AltText = "Mass Effect", CategoryID = 6, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/masseffect_logo.png", LongDescription = "Mass Effect'in devamı olan Mass Effect 2, 26 ocak 2010 tarihinde piyasaya sürülmüştür. Mass Effect 2'de birinci oyundan kalan kayıt dosyalarını aktarabilirsiniz ki bu sizin oyun boyunca yapacağınız şeyleride değiştirecektir.Mass Effect serisi Mass Effect 2 ile beraber IGN ve EA Games Entertainment açıklamasıyla tüm platformlarda 34.5 milyon satarak iyi bir başarı elde etmiştir.Aynı zamanda EA Games in en çok kazandıran ilk 5 oyunu arasında yer almaktadır.", Name = "Mass Effect", ShortDescription = "Oyun gelecekte 2183 yılında geçmektedir. Oyuncu Commander Shepard isimli bir karakteri canlandirir ve bu karakter galaksiyi gemisi SSV Normandy ile araştırma altinda tutmaktadir.", SupplierID = 2, UnitPrice = 100m, UnitsInStock = 0 },
                        new { ProductID = 18, AltText = "Dragon Age: Origins", CategoryID = 3, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/da-origins_logo.png", LongDescription = "Kurgusal Ferelden krallığında, sivil sürtüşmelerin yaşandığı bir dönemde kurgulanmış oyunda oyuncular; bir elf, insan ve cüce geçmişinden gelen bir savaşçı, büyücü veya bir hırsız rolünde; krallığa yaklaşmakta olan ve 'Darkspawn' (Zebâni) olarak bilinen şeytani güçlerin istilasına karşı krallığı bir araya getirmekle görevlidirler. Oyuncunun karakteri, eskilerden beri var olan 'Grey Warden' tertibinde silâh altına alınır. Gri Muhafızlar, Zebâni olarak bilinen şeytani güçlere karşı gelip, 'Yıkım' (Blight) olarak bilinen, zebânileri komuta eden Şahlanmış Şeytan'ı (Archdemon) yenmekle görevlendirilmişlerdir. Oyun, kuş bakışı perspektife değiştirilebilen üçüncü şahıs perspektifi ile oynanır. Oyun boyunca oyuncular, oyunun ana hikâyesinde ve ilerlenmesinde önemli rol oynayan ve maceraları boyunca eşlik edecek çeşitli karakterler ile karşılaşırlar.", Name = "Dragon Age: Origins", ShortDescription = "Dragon Age: Origins (Türkçesi: Ejderha Çağı: Başlangıçlar), BioWare tarafından geliştirilen ve Electronic Arts tarafından dağıtılan tek oyunculu rol yapma video oyunudur. Dragon Age serisinin ilk oyunu olup Kasım 2009'da Microsoft Windows, PlayStation 3 ve Xbox 360; 21 Aralık 2009'da ise OS X için satışa sunulmuştur.", SupplierID = 2, UnitPrice = 54m, UnitsInStock = 0 },
                        new { ProductID = 19, AltText = "Crysis 3", CategoryID = 1, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/crysis3_logo.png", LongDescription = "Crysis 3, Crysis 2'den 24 yıl sonrasında yani 2047 yılında ve bir kez daha New York şehrinde geçiyor. İkinci oyunda gerçekleşen büyük savaşın ardından Prophet, Crynet tarafından hapse atılır ve Cephler (uzaylılar) tarafından dünya üzerinde o ana kadar görülmemiş en büyük işgal gerçekleştirilir. Ayrıca New York, Crysis 2'nin sonundaki büyük patlamadan sonra sular altında kalır ve şehir ormanımsı bir hal alır. Bu olaylardan sonra şehrin bir kısmı Cell Corporation tarafından Nanodome adı verilen dev bir fanusun içine alınır. Nanodome içerisindeki alana ise 'New York City Liberty Dome' adı verilir. Cell Corporation bu fanusun amacının karantina bölgesi oluşturmak ve insanları uzaylılardan korumak olduğunu söylese de, Prophet, Cell Corporation'ın Nanodome içerisinde dünyayı ele geçirmek için teknoloji geliştirdiğini öngörür. Crysis 3'te ana karakter Prophet olacak. Prophet bu defa intikam için savaşacak.", Name = "Crysis 3", ShortDescription = "Crysis 3, Crytek tarafından geliştirilmiş, Electronic Arts tarafından ise yayımcılığı yapılmış olan bilim kurgu türü video oyunudur. Crysis 3 serinin diğer oyunları gibi Türkçe alt yazı ve seslendirme içermektedir.", SupplierID = 2, UnitPrice = 54m, UnitsInStock = 0 },
                        new { ProductID = 20, AltText = "Star Wars Battlefront", CategoryID = 1, Discount = 0m, ImageUrl = "/images/ProductPictures/Steam/starwars-battlefron_logo.png", LongDescription = "Oyunda hikâye modu bulunmamakta ve genel olarak çok oyunculu bölüme odaklı. Ama oyuncuların offline olarak, tek başlarına oynayabilecekleri görevler de bulunuyor. Ayrıca oyuncular bu görevleri arkadaşlarıyla birlikte Co-op (kooperatif) olarak da oynayabilirler. Co-op (kooperatif) görevler konsollarda split screen olarak oynanabilir. Oyun hem birinci şahıs nişancı hem de üçüncü şahıs nişancı olarak oynanabiliyor. Oyuncular Rebel Alliance (Asi Birliği) ya da Stormtrooper taraflarından birini seçerek birbirleriyle savaşıyorlar. Ayrıca Darth Vader ve Boba Fett gibi Star Wars evreninin önemli karakterleri de oynanabiliyor. Oyuncular karakterlerini özelleştirebilirler. Hoth, Endor, Tatooine, Sullust gezegenlerinde geçecek olan oyunda 12 tane harita bulunuyor. Haritalar 40 oyuncuyu destekliyor. Oyunda X-Wing, Millennium Falcon, TIE Fighters ve AT-ST Walker gibi oyuncuların kullanabileceği birçok araç bulunuyor.", Name = "Star Wars Battlefront", ShortDescription = "Star Wars: Battlefront, DICE tarafından geliştirilen, Electronic Arts'ın ise yayımcılığı yaptığı video oyunudur.", SupplierID = 2, UnitPrice = 100m, UnitsInStock = 0 }
                    );
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.RecentlyView", b =>
                {
                    b.Property<int>("RecentlyViewID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerID")
                        .IsRequired();

                    b.Property<string>("Notes")
                        .HasMaxLength(150);

                    b.Property<int>("ProductID");

                    b.Property<DateTime>("ViewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RecentlyViewID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProductID");

                    b.ToTable("RecentlyViews");
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(5000);

                    b.Property<string>("CustomerID")
                        .IsRequired();

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<int>("ProductID");

                    b.Property<int>("Rate");

                    b.HasKey("ReviewID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProductID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.ShippingDetail", b =>
                {
                    b.Property<int>("ShippingDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Mobile")
                        .HasMaxLength(30);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(25);

                    b.Property<string>("Province")
                        .HasMaxLength(30);

                    b.HasKey("ShippingDetailID");

                    b.ToTable("ShippingDetails");
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(150);

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ContactName")
                        .HasMaxLength(50);

                    b.Property<string>("ContactTitle")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("Fax")
                        .HasMaxLength(20);

                    b.Property<string>("Mobile")
                        .HasMaxLength(20);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new { SupplierID = 1, CompanyName = "Steam", ContactName = "Gabe Newell", ContactTitle = "Founder" },
                        new { SupplierID = 2, CompanyName = "Electronic Arts", ContactName = "Trip Hawkins", ContactTitle = "Founder" }
                    );
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.WishList", b =>
                {
                    b.Property<int>("WishListID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerID")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<int>("ProductID");

                    b.HasKey("WishListID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProductID");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new { UserId = "ed569773-7f8d-4712-9b43-5ae3ad709632", RoleId = "bace2fe6-0871-41bd-b614-931227376627" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.Customer", b =>
                {
                    b.HasOne("GameStation.Entity.Concrete.CustomIdentityUser", "CustomIdentityUser")
                        .WithOne("Customer")
                        .HasForeignKey("GameStation.Entity.Concrete.Customer", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.Order", b =>
                {
                    b.HasOne("GameStation.Entity.Concrete.OrderDetail", "OrderDetail")
                        .WithMany("Orders")
                        .HasForeignKey("OrderDetailID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameStation.Entity.Concrete.Payment", "Payment")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameStation.Entity.Concrete.ShippingDetail", "ShippingDetail")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingDetailID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.OrderDetail", b =>
                {
                    b.HasOne("GameStation.Entity.Concrete.Customer", "Customer")
                        .WithMany("OrderDetails")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameStation.Entity.Concrete.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.Payment", b =>
                {
                    b.HasOne("GameStation.Entity.Concrete.PaymentType", "PaymentType")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.Product", b =>
                {
                    b.HasOne("GameStation.Entity.Concrete.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameStation.Entity.Concrete.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.RecentlyView", b =>
                {
                    b.HasOne("GameStation.Entity.Concrete.Customer", "Customer")
                        .WithMany("RecentlyViews")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameStation.Entity.Concrete.Product", "Product")
                        .WithMany("RecentlyViews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.Review", b =>
                {
                    b.HasOne("GameStation.Entity.Concrete.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameStation.Entity.Concrete.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GameStation.Entity.Concrete.WishList", b =>
                {
                    b.HasOne("GameStation.Entity.Concrete.Customer", "Customer")
                        .WithMany("WishLists")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameStation.Entity.Concrete.Product", "Product")
                        .WithMany("WishLists")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("GameStation.Entity.Concrete.CustomIdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GameStation.Entity.Concrete.CustomIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GameStation.Entity.Concrete.CustomIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("GameStation.Entity.Concrete.CustomIdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GameStation.Entity.Concrete.CustomIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GameStation.Entity.Concrete.CustomIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
